---
# tasks file for sonar

- block:
    - name: Download sonarqube
      get_url:
        url: "{{ sonar_url }}"
        dest: "{{ sonar_dest }}"
  rescue:
  - debug: msg="Sonarqube download failed due to error in the url"
  - debug: msg="Sonarqube download and installation failed"

- name: Unarchive the config zip file in the same folder
  unarchive:
    src: "{{ sonar_zip_path }}"
    dest: "{{ sonar_unarchive_path }}"
    remote_src: yes

- name: start sonar on default port
  shell: "{{ sonar_start }}"
  args:
    chdir: "{{ sonar_start_dir }}"
    warn: false

- debug: 
    msg: 
    - Sonar is successfully installed
    - Sonar is up and running
